import type { Metadata } from "next";
import { Orbitron, Share_Tech_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import { cn } from "@/lib/utils";




const shareTechMono = Share_Tech_Mono({subsets:['latin'],variable:'--font-share-tech-mono', weight:['400'], style:['normal']});
const orbitron = Orbitron({subsets:['latin'],variable:'--font-orbitron', weight:['400'], style:['normal']});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
      <html lang="ru" className={cn(shareTechMono.variable, orbitron.variable)}>
        <body>
          <Providers>{children}</Providers>
        </body>
      </html>
    );
}
